buy_me_a_coffee: pgarachne
custom: ["https://www.paypal.com/donate/?hosted_button_id=YUAEVQGPYZU8U", "https://revolut.me/zbynekvanzura", "https://wise.com/pay/me/zbynekv17", "https://app.binance.com/uni-qr/DbrFdVHA", "https://github.com/heptau/pgarachne/blob/master/docs/index.html#support"]
