-- PgArachne Quick Start — Hello World, run once in your database
-- (after sql/schema.sql):  psql -d my_database -f hello_world.sql

-- A login role for the web page. Change the password for anything real!
DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'demo_user') THEN
        CREATE ROLE demo_user LOGIN PASSWORD 'user_password';
    END IF;
END $$;

CREATE SCHEMA IF NOT EXISTS api;
GRANT USAGE ON SCHEMA api TO demo_user;

-- Step 4 + 6: Hello World with a parameter ("name"). When "notify" is true, the
-- function also publishes the greeting on the "hello" channel (received by the
-- SSE endpoint).
CREATE OR REPLACE FUNCTION api.hello_world(payload jsonb DEFAULT '{}'::jsonb)
RETURNS json
LANGUAGE plpgsql AS $$
DECLARE
    greeting text := 'Hello, ' || COALESCE(payload->>'name', 'World') || '!';
BEGIN
    IF COALESCE((payload->>'notify')::boolean, false) THEN
        PERFORM pg_notify('hello', json_build_object('message', greeting)::text);
    END IF;
    RETURN json_build_object('message', greeting);
END;
$$;

-- Step 7: a function that returns a file (path, content, mime_type, store_only).
CREATE OR REPLACE FUNCTION api.hello_world_file(payload jsonb DEFAULT '{}'::jsonb)
RETURNS TABLE (path text, content bytea, mime_type text, store_only boolean)
LANGUAGE sql AS $$
    SELECT 'hello-world.md',
           convert_to(
               '# Hello, ' || COALESCE(payload->>'name', 'World') || E'!\n\n'
               || 'This file was generated by PostgreSQL at ' || now() || E'.\n',
               'UTF8'),
           'text/markdown',
           false;
$$;

-- PostgreSQL decides who may call what: grant EXECUTE on exactly these functions.
GRANT EXECUTE ON FUNCTION api.hello_world(jsonb)      TO demo_user;
GRANT EXECUTE ON FUNCTION api.hello_world_file(jsonb) TO demo_user;
